### PR TITLE
Milotype translate 1

### PR DESCRIPTION
**Pull request by milotype**
i'll also be adding lots of croatian translations for the addons-sources.

### CODE REVIEW

**Comment by prculley** [comment]
I'm sorry you spent the time on this, but these files are generated by a script from other data, so your work will be lost the first time someone runs the script again.

If you want to get all the addons to show up here as properly translated, you have to do the translations for each addon.  That way when the script generates this file, it shows up here properly translated.
Follow instructions https://gramps-project.org/wiki/index.php/Addons_development#Get_translators_to_translate_your_addon_into_multiple_languages to do the addon translations, and submit the results as a PR.  You can do several (or all) addons at once when creating the PR.

**Comment by milotype** [comment]
Thank you for the info – I didn’t know that. Should I simply delete the branch „milotype:milotype-translate-1”?

Actually i do have most addons translated – 2 or 3 are not done yet. 
If I may, please let me explain my translations.
As most addon folders don’t have their own .pot files, i usually duplicated the german .po file. As I checked other languages of each addon, I finally always took the .po file of the language which had the highest number of strings (yes, some .po files are trimmed in diverse languages !?).
I changed the first couple of lines of the metadata (with BBedit) and then edited the .po files with Poedit. I did the necessary changes for Project, Language and Plural-forms.

1. I’ve already forked „addons-source” into my „milotype” repository.
2. I’ve generated a branch „milotpe-translate-addons-source”.
3. I’ll add or update the „hr-local.po” files separately into each addon subfolder of my branch.
4. I’ll make a „New pull request” for the whole branch.

Would that be an appropriate procedure?

**Comment by prculley** [comment]
Generally a good procedure, except that you should really be creating and updating from an .pot file.
The reason some .po files have fewer strings is likely that they were made from out of date .pot.

If you 
./make.py gramps50 init AddonName
that should generate a current .pot, then 
./make.py gramps50 init NewProjectName hr
if there is no hr-local.po file.  Then do 
./make.py gramps50 update NewProjectName hr
which  copies any new strings (and removes unused ones) from the .pot to the po as well as grabbing common translations from Gramps.  If the hr-local.pr already had translations, they are preserved.
Then do your manual edits, commit the new hr-local.po.

**Comment by milotype** [comment]
:-((  this is too complex for me. as mentioned before, i'm no programmer! i simply download files, translate them and upoad them back.
so, i'd like to propose two alternatives:
1. i do it my way (btw, i am quite pedantic in my work)
2. somebody generates (maybe automatically?) all the necessary .pot files, and adds them to the appropriate folders (just as there is a .pot file for gramps itself)
please let me know how to proceed. in the mean time i'll keep translating …
thank you!

**Pull request closed without merging**
