### PR TITLE
New Birth order plugin

### PR DESCRIPTION
**Pull request by prculley**
birthorder

### CODE REVIEW

**Comment by johnbickmore** [comment]
Very useful 👍

**Comment by sam-m888** [comment]
Hi Paul,

Testing shows the following few issues:

Run the tool and accept all.

re-run the tool and dismiss the notice that "No families need sorting"

Select the "Accept" button and get the following error:


1620094: ERROR: grampsapp.py: line 143: Unhandled exception
Traceback (most recent call last):
  File "/home/grampsdev/.gramps/gramps50/plugins/BirthOrder/birthorder.py",
line 138, in on_accept
    orig_ref_list = self.family.get_child_ref_list()
AttributeError: 'NoneType' object has no attribute 'get_child_ref_list'


Or select the up arrow button

1744027: ERROR: grampsapp.py: line 143: Unhandled exception
Traceback (most recent call last):
  File "/home/grampsdev/.gramps/gramps50/plugins/BirthOrder/birthorder.py",
line 211, in on_up
    pos = self.ch_sorted_index()
  File "/home/grampsdev/.gramps/gramps50/plugins/BirthOrder/birthorder.py",
line 206, in ch_sorted_index
    ch_path = self.ch_view_s.get_selection().get_selected_rows()[1][0]
IndexError: list index out of range


or down  arrow button

1773450: ERROR: grampsapp.py: line 143: Unhandled exception
Traceback (most recent call last):
  File "/home/grampsdev/.gramps/gramps50/plugins/BirthOrder/birthorder.py",
line 220, in on_down
    pos = self.ch_sorted_index()
  File "/home/grampsdev/.gramps/gramps50/plugins/BirthOrder/birthorder.py",
line 206, in ch_sorted_index
    ch_path = self.ch_view_s.get_selection().get_selected_rows()[1][0]
IndexError: list index out of range

**Comment by prculley** [comment]
@sam-m888 Thanks for the review.  I am always surprised when someone manages to figure out a case I never considered.  A good example of cognitive blindness.  I think I've fixed the issues you spotted now.

**Comment by sam-m888** [comment]
Your welcome,  an extra set of eyes always helps 👍 

Thank you for the new addon 🥇

**Pull request merged**
